
/* ==================== 方剂数据 ====================
   索引 0-19  → 第 1 档（医力 1-1000）
   索引 20-39 → 第 2 档（医力 1001-2000）
   索引 40-59 → 第 3 档（医力 2001-3000）
   索引 60+   → 第 4 档（医力 3000+，预留）
   ==================================================== */
var FORMULAS = [
    /* ---- 第 1 档：太阳病基础方 ---- */
    { name: '桂枝汤', patient: 'images/patients/patient_guizhi.webp',
      speak: '大夫，我发热，一直出汗，特别怕风。',
      s: { head: ['头痛'], chest: ['发热','汗出','恶风'], belly: [], limbs: [], pulse: ['脉浮缓'] } },
    { name: '桂枝加葛根汤', patient: 'images/patients/patient_guizhi.webp',
      speak: '大夫，我后背脖子僵得难受，发热出汗，还怕风。',
      s: { head: ['项背强几几'], chest: ['发热','汗出','恶风'], belly: [], limbs: [], pulse: ['脉浮缓'] } },
    { name: '麻黄汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '大夫，我头痛发热，浑身骨节都疼，一点汗都出不来，还喘。',
      s: { head: ['头痛'], chest: ['发热','无汗','恶风','喘'], belly: [], limbs: ['身疼','腰痛','骨节疼痛'], pulse: ['脉浮紧'] } },
    { name: '麻黄附子细辛汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '大夫，我发热怕冷，浑身没劲，脉却沉得很。',
      s: { head: [], chest: ['发热','恶寒'], belly: [], limbs: ['倦卧'], pulse: ['脉沉'] } },
    { name: '葛根汤', patient: 'images/patients/patient_gegen.webp',
      speak: '大夫，我脖子后背僵硬得难受，发热怕冷，不出汗。',
      s: { head: ['项背强几几'], chest: ['发热','无汗','恶风'], belly: [], limbs: [], pulse: ['脉浮'] } },
    { name: '葛根芩连汤', patient: 'images/patients/patient_gegen.webp',
      speak: '大夫，我一直拉肚子，喘气还出汗，脉跳得很快。',
      s: { head: [], chest: ['喘','汗出'], belly: ['下利不止'], limbs: [], pulse: ['脉促'] } },
    { name: '小青龙汤', patient: 'images/patients/patient_xiaoqinglong.webp',
      speak: '大夫，我怕冷发热，一直咳嗽，还干呕。',
      s: { head: [], chest: ['发热','恶寒','心下有水气','咳'], belly: [], limbs: ['干呕'], pulse: [] } },
    { name: '射干麻黄汤', patient: 'images/patients/patient_xiaoqinglong.webp',
      speak: '大夫，我咳嗽气往上冲，喉咙里像水鸡叫一样响。',
      s: { head: [], chest: ['咳而上气','喉中水鸡声'], belly: [], limbs: [], pulse: [] } },
    { name: '大青龙汤', patient: 'images/patients/patient_daqinglong.webp',
      speak: '大夫，我发热怕冷，浑身疼得厉害，一点汗都出不来，心里烦躁得很。',
      s: { head: ['烦躁'], chest: ['发热','恶寒','身疼痛','不汗出'], belly: [], limbs: [], pulse: [] } },
    { name: '越婢汤', patient: 'images/patients/patient_daqinglong.webp',
      speak: '大夫，我全身都肿了，怕风，一直出汗。',
      s: { head: [], chest: ['一身悉肿','恶风','续自汗出'], belly: [], limbs: [], pulse: ['脉浮'] } },
    { name: '小柴胡汤', patient: 'images/patients/patient_xiaochaihu.webp',
      speak: '大夫，我一会冷一会热，胸口两肋胀得难受，不想吃饭，老想吐。',
      s: { head: ['心烦'], chest: ['往来寒热','胸胁苦满'], belly: ['不欲饮食','喜呕'], limbs: [], pulse: ['脉弦'] } },
    { name: '柴胡桂枝汤', patient: 'images/patients/patient_xiaochaihu.webp',
      speak: '大夫，我有点发热有点怕冷，四肢关节疼，还有点想吐。',
      s: { head: [], chest: ['发热微恶寒','支节烦疼','微呕','心下支结'], belly: [], limbs: [], pulse: [] } },
    { name: '大柴胡汤', patient: 'images/patients/patient_dachaihu.webp',
      speak: '大夫，我一会冷一会热，心口下面堵得慌，又吐又拉。',
      s: { head: [], chest: ['往来寒热'], belly: ['心下痞硬','呕吐','下利'], limbs: [], pulse: ['脉弦'] } },
    { name: '柴胡加龙骨牡蛎汤', patient: 'images/patients/patient_dachaihu.webp',
      speak: '大夫，我胸口胀得慌，心烦害怕，小便不通畅，还胡言乱语。',
      s: { head: ['烦惊'], chest: ['胸满','谵语'], belly: ['小便不利'], limbs: ['一身尽重'], pulse: [] } },
    { name: '白虎汤', patient: 'images/patients/patient_baihu.webp',
      speak: '大夫，我浑身滚烫，出大汗，渴得厉害。',
      s: { head: [], chest: ['身大热','汗大出','口大渴'], belly: [], limbs: [], pulse: ['脉洪大'] } },
    { name: '白虎加人参汤', patient: 'images/patients/patient_baihu.webp',
      speak: '大夫，我出大汗以后特别渴，怎么喝都不解渴。',
      s: { head: [], chest: ['大汗出','大烦渴不解','背微恶寒'], belly: [], limbs: [], pulse: ['脉洪大'] } },
    { name: '竹叶石膏汤', patient: 'images/patients/patient_baihu.webp',
      speak: '大夫，我病刚好，浑身没劲，气往上逆，想吐。',
      s: { head: [], chest: ['虚羸少气','气逆欲吐'], belly: [], limbs: [], pulse: [] } },
    { name: '大承气汤', patient: 'images/patients/patient_dachengqi.webp',
      speak: '大夫，我肚子胀痛，大便好几天不通了，下午发热，手脚出汗。',
      s: { head: ['潮热'], chest: [], belly: ['腹满痛','大便不通'], limbs: ['手足汗出'], pulse: [] } },
    { name: '麻子仁丸', patient: 'images/patients/patient_dachengqi.webp',
      speak: '大夫，我小便特别多，大便干硬得解不出来。',
      s: { head: [], chest: [], belly: ['大便硬','小便数'], limbs: [], pulse: ['脉浮而涩'] } },
    { name: '桃核承气汤', patient: 'images/patients/patient_dachengqi.webp',
      speak: '大夫，我小肚子又急又结，人烦得发狂。',
      s: { head: ['其人如狂'], chest: [], belly: ['少腹急结'], limbs: [], pulse: [] } },

    /* ---- 第 2 档：三阴病 + 杂病 ---- */
    { name: '小承气汤', patient: 'images/patients/patient_xiaochengqi.webp',
      speak: '大夫，我肚子胀得厉害，大便干硬，心里烦躁。',
      s: { head: ['微烦'], chest: [], belly: ['腹大满','大便硬'], limbs: [], pulse: [] } },
    { name: '大黄牡丹汤', patient: 'images/patients/patient_xiaochengqi.webp',
      speak: '大夫，我小肚子肿起来一块，一按就疼，还发热出汗怕冷。',
      s: { head: [], chest: ['时时发热','自汗出','复恶寒'], belly: ['少腹肿痞','按之即痛'], limbs: [], pulse: [] } },
    { name: '调胃承气汤', patient: 'images/patients/patient_tiaowei.webp',
      speak: '大夫，我身上发热，肚子胀。',
      s: { head: [], chest: ['蒸蒸发热'], belly: ['腹胀满'], limbs: [], pulse: [] } },
    { name: '大黄甘草汤', patient: 'images/patients/patient_tiaowei.webp',
      speak: '大夫，我吃完东西马上就吐。',
      s: { head: [], chest: [], belly: ['食已即吐'], limbs: [], pulse: [] } },
    { name: '理中汤', patient: 'images/patients/patient_lizhong.webp',
      speak: '大夫，我肚子胀，又吐又拉，不想吃饭，肚子一阵一阵疼。',
      s: { head: [], chest: [], belly: ['腹满','吐利','不欲食','时腹自痛'], limbs: [], pulse: [] } },
    { name: '甘草干姜汤', patient: 'images/patients/patient_lizhong.webp',
      speak: '大夫，我咽干烦躁，又吐又逆。',
      s: { head: ['烦躁'], chest: ['咽中干'], belly: ['吐逆'], limbs: [], pulse: [] } },
    { name: '吴茱萸汤', patient: 'images/patients/patient_lizhong.webp',
      speak: '大夫，我吃点东西就想吐，还吐清涎，头也疼得厉害。',
      s: { head: ['头痛'], chest: [], belly: ['食谷欲呕','干呕吐涎沫'], limbs: [], pulse: [] } },
    { name: '四逆汤', patient: 'images/patients/patient_sini.webp',
      speak: '大夫，我手脚冰凉，拉肚子都是没消化的东西。',
      s: { head: [], chest: [], belly: ['下利清谷'], limbs: ['四肢厥逆'], pulse: ['脉微欲绝'] } },
    { name: '通脉四逆汤', patient: 'images/patients/patient_sini.webp',
      speak: '大夫，我拉肚子全是没消化的东西，手脚冰凉，可身上反而发热，脸也红。',
      s: { head: ['面色赤'], chest: ['里寒外热','身反不恶寒'], belly: ['下利清谷'], limbs: ['手足厥逆'], pulse: ['脉微欲绝'] } },
    { name: '真武汤', patient: 'images/patients/patient_zhenwu.webp',
      speak: '大夫，我头晕心慌，身上肌肉跳，小便不通畅。',
      s: { head: ['头眩'], chest: ['心下悸','身瞤动'], belly: ['小便不利'], limbs: [], pulse: [] } },
    { name: '苓桂术甘汤', patient: 'images/patients/patient_zhenwu.webp',
      speak: '大夫，我胸口下面胀满，气往上冲，一起身就头晕。',
      s: { head: ['起则头眩'], chest: ['心下逆满','气上冲胸'], belly: [], limbs: [], pulse: ['脉沉紧'] } },
    { name: '五苓散', patient: 'images/patients/patient_wuling.webp',
      speak: '大夫，我渴得想喝水，喝了又吐出来，小便不通畅。',
      s: { head: [], chest: ['渴欲饮水','水入则吐'], belly: ['小便不利'], limbs: [], pulse: [] } },
    { name: '猪苓汤', patient: 'images/patients/patient_wuling.webp',
      speak: '大夫，我发热口渴老想喝水，小便不通畅，心烦得睡不着。',
      s: { head: ['心烦不得眠'], chest: ['发热','渴欲饮水'], belly: ['小便不利'], limbs: [], pulse: ['脉浮'] } },
    { name: '半夏泻心汤', patient: 'images/patients/patient_banxia.webp',
      speak: '大夫，我心口堵得慌，又吐又肠鸣，还拉肚子。',
      s: { head: [], chest: [], belly: ['心下痞满','呕而肠鸣','下利'], limbs: [], pulse: [] } },
    { name: '小陷胸汤', patient: 'images/patients/patient_banxia.webp',
      speak: '大夫，我心口下面按一下就疼，脉浮滑。',
      s: { head: [], chest: ['正在心下','按之则痛'], belly: [], limbs: [], pulse: ['脉浮滑'] } },
    { name: '栀子豉汤', patient: 'images/patients/patient_zhizi.webp',
      speak: '大夫，我心里烦得睡不着觉，辗转反侧。',
      s: { head: ['虚烦不得眠','心中懊憹'], chest: [], belly: [], limbs: [], pulse: [] } },
    { name: '茵陈蒿汤', patient: 'images/patients/patient_yinchen.webp',
      speak: '大夫，我浑身发黄，像橘子皮那么黄，小便不通畅，肚子有点胀。',
      s: { head: [], chest: ['身黄如橘子色'], belly: ['小便不利','腹微满'], limbs: [], pulse: [] } },
    { name: '当归四逆汤', patient: 'images/patients/patient_dangguisini.webp',
      speak: '大夫，我手脚冰凉得厉害，怎么也暖不热。',
      s: { head: [], chest: [], belly: [], limbs: ['手足厥寒'], pulse: ['脉细欲绝'] } },
    { name: '小建中汤', patient: 'images/patients/patient_xiaojianzhong.webp',
      speak: '大夫，我肚子一阵一阵绞痛，心里慌得很。',
      s: { head: ['心中悸而烦'], chest: [], belly: ['腹中急痛'], limbs: [], pulse: [] } },
    { name: '炙甘草汤', patient: 'images/patients/patient_xiaojianzhong.webp',
      speak: '大夫，我心慌得厉害，脉跳一下停一下。',
      s: { head: [], chest: ['心动悸'], belly: [], limbs: [], pulse: ['脉结代'] } },

    /* ---- 第 3 档：金匮要略方 ---- */
    { name: '栝蒌桂枝汤', patient: 'images/patients/patient_guizhi.webp',
      speak: '我像是感冒了，身上出汗，脖子后背僵硬发紧，转动不灵活，浑身拘紧不舒服。',
      s: { head: ['身体强几几然'], chest: ['汗出'], belly: [], limbs: ['身体拘紧'], pulse: ['脉反沉迟'] } },
    { name: '麻黄加术汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '我全身酸痛，酸胀烦扰，浑身难受，身上裹着湿冷感。',
      s: { head: [], chest: ['身烦疼'], belly: [], limbs: ['身重'], pulse: ['脉浮紧'] } },
    { name: '麻杏薏甘汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '我浑身到处疼，有点发烧，每到傍晚疼得更厉害。之前出汗吹风，或是经常贪凉。',
      s: { head: [], chest: ['发热','日晡所剧'], belly: [], limbs: ['一身尽疼'], pulse: [] } },
    { name: '防己黄芪汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '我身体沉重乏力，稍微一动就出汗，很怕吹风，身上酸痛。',
      s: { head: [], chest: ['汗出','恶风'], belly: [], limbs: ['身重'], pulse: ['脉浮'] } },
    { name: '桂枝附子汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '我身上疼得厉害，翻身都费劲，没有恶心，也不口渴。',
      s: { head: [], chest: ['不呕','不渴'], belly: [], limbs: ['身体疼烦','不能自转侧'], pulse: ['脉浮虚而涩'] } },
    { name: '白术附子汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '我浑身关节疼，大便干难解，但小便排尿正常。',
      s: { head: [], chest: [], belly: ['大便坚','小便自利'], limbs: ['骨节疼'], pulse: [] } },
    { name: '甘草附子汤', patient: 'images/patients/patient_mahuang.webp',
      speak: '我关节扯着疼，弯不了伸不开，一碰就剧痛；容易出汗，一动就气短，小便不畅，怕冷不想脱衣服，身上有点浮肿。',
      s: { head: [], chest: ['汗出','短气','恶风不欲去衣'], belly: ['小便不利'], limbs: ['骨节疼烦','掣痛不得屈伸','身微肿'], pulse: [] } },
    { name: '一物瓜蒂汤', patient: 'images/patients/patient_baihu.webp',
      speak: '夏天受凉水之后，身上发热、浑身酸痛沉重，浑身乏力。',
      s: { head: [], chest: ['身热'], belly: [], limbs: ['疼重'], pulse: ['脉微弱'] } },
    { name: '百合知母汤', patient: 'images/patients/patient_zhizi.webp',
      speak: '之前吃过发汗药之后，心烦燥热，口渴，心里难受，坐卧不安，食欲时好时坏。',
      s: { head: ['心烦'], chest: ['口渴'], belly: ['食欲时好时坏'], limbs: ['坐卧不安'], pulse: [] } },
    { name: '滑石代赭汤', patient: 'images/patients/patient_zhizi.webp',
      speak: '之前用了泻药之后，胃里不舒服，容易恶心反胃，小便短少发黄，心里烦躁。',
      s: { head: ['心烦'], chest: ['胃中不适'], belly: ['恶心反胃','小便短赤'], limbs: [], pulse: [] } },
    { name: '百合鸡子汤', patient: 'images/patients/patient_zhizi.webp',
      speak: '之前吃过催吐药，胃里空虚难受，心烦睡不着，心里一阵阵燥热。',
      s: { head: ['心烦不眠'], chest: ['胃中空虚'], belly: [], limbs: [], pulse: [] } },
    { name: '百合地黄汤', patient: 'images/patients/patient_zhizi.webp',
      speak: '吃饭没胃口，想吃又不想吃；坐也不舒服、躺也不安；一会觉得冷一会觉得热，口苦，小便颜色偏红。',
      s: { head: ['口苦'], chest: ['如寒无寒','如热无热'], belly: ['饮食或有美时','或有不欲闻食臭时','小便赤'], limbs: ['坐卧不安'], pulse: [] } },
    { name: '百合洗方', patient: 'images/patients/patient_zhizi.webp',
      speak: '这个病拖了一个月，一直不好，现在口渴明显，喝了水也不解渴。',
      s: { head: [], chest: ['口渴'], belly: [], limbs: [], pulse: [] } },
    { name: '栝蒌牡蛎散', patient: 'images/patients/patient_zhizi.webp',
      speak: '一直口渴，怎么喝水都缓解不明显，心烦燥热。',
      s: { head: ['心烦'], chest: ['渴不差'], belly: [], limbs: [], pulse: [] } },
    { name: '百合滑石散', patient: 'images/patients/patient_zhizi.webp',
      speak: '原先没有发烧，后来开始身上发热，心烦，小便短黄。',
      s: { head: ['心烦'], chest: ['发热'], belly: ['小便短黄'], limbs: [], pulse: [] } },
    { name: '甘草泻心汤', patient: 'images/patients/patient_banxia.webp',
      speak: '总想睡觉，但又睡不着，躺卧都不安稳；咽喉溃烂疼，说话声音嘶哑；不想吃饭，闻到饭菜味道就难受；脸上颜色一阵红一阵暗。',
      s: { head: ['默默欲眠','目不得闭'], chest: ['声喝'], belly: ['不欲饮食','恶闻食臭'], limbs: ['卧起不安','面目乍赤乍黑乍白'], pulse: [] } },
    { name: '苦参汤', patient: 'images/patients/patient_banxia.webp',
      speak: '下身溃烂疼痛，虽然病灶在下，但咽喉发干不适。',
      s: { head: [], chest: ['咽干'], belly: [], limbs: ['下部蚀烂'], pulse: [] } },
    { name: '雄黄熏方', patient: 'images/patients/patient_banxia.webp',
      speak: '肛门部位溃烂疼痛，局部灼热不适。',
      s: { head: [], chest: [], belly: [], limbs: ['肛部蚀烂'], pulse: [] } },
    { name: '赤小豆当归散', patient: 'images/patients/patient_yinchen.webp',
      speak: '身上不发烧，心里有点烦，只想躺着，容易出汗；发病三四天眼睛发红，到七八天眼周发黑；胃口反而变好，体内已经成脓。',
      s: { head: ['微烦','默默但欲卧'], chest: ['无热','汗出'], belly: ['能食'], limbs: ['目赤如鸠眼','目四眦黑'], pulse: ['脉数'] } },
    { name: '升麻鳖甲汤', patient: 'images/patients/patient_banxia.webp',
      speak: '脸上长出红斑，像织锦花纹一样，咽喉疼，咳嗽、吐脓血。',
      s: { head: ['面赤斑斑如锦纹'], chest: ['咽喉痛','唾脓血'], belly: [], limbs: [], pulse: [] } }
];